<a href="https://colab.research.google.com/github/JimStrawberry/AI/blob/master/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/JimStrawberry/AI/refs/heads/master/ML/dataset/Salary_Data2.csv"
data = pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [ ]:
data["EducationLevel"] = data["EducationLevel"].map({"高中以下": 0, "大學": 1, "碩士以上": 2})
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [ ]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()
city_encoded = onehotencoder.fit_transform(data[["City"]]).toarray()
city_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
data[["CityA", "CityB", "CityC"]] = city_encoded
data

YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [ ]:
data.drop(["CityC", "City"], axis=1, inplace=True)
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [ ]:
from sklearn.model_selection import train_test_split

x = data[["YearsExperience", "EducationLevel", "CityA", "CityB"]]
y = data["Salary"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=23)
len(x_train), len(x_test)
x_train.to_numpy()
x_test.to_numpy()

array([[ 1.5,  2. ,  0. ,  0. ],
       [ 3.6,  1. ,  1. ,  0. ],
       [10. ,  2. ,  0. ,  1. ],
       [ 8. ,  1. ,  0. ,  0. ],
       [ 3.5,  1. ,  1. ,  0. ],
       [ 2.1,  0. ,  1. ,  0. ],
       [ 5. ,  0. ,  1. ,  0. ],
       [ 4.2,  1. ,  1. ,  0. ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[ 0.73125007,  0.89802651, -1.07417231, -0.34641016],
       [ 1.64633396,  0.89802651, -1.07417231,  2.88675135],
       [ 0.65499308,  0.89802651, -1.07417231, -0.34641016],
       [ 0.80750706,  0.89802651, -1.07417231, -0.34641016],
       [-0.22196231, -1.61644772,  0.93094934, -0.34641016],
       [-1.48020266,  0.89802651, -1.07417231, -0.34641016],
       [-0.14570532, -1.61644772,  0.93094934, -0.34641016],
       [ 1.03627803, -0.3592106 , -1.07417231, -0.34641016],
       [ 0.15932264,  0.89802651,  0.93094934, -0.34641016],
       [ 0.31183662,  0.89802651,  0.93094934, -0.34641016],
       [ 0.96002104, -0.3592106 , -1.07417231, -0.34641016],
       [-1.02266071, -0.3592106 ,  0.93094934, -0.34641016],
       [-1.70897363,  0.89802651, -1.07417231, -0.34641016],
       [-0.67950425, -0.3592106 ,  0.93094934, -0.34641016],
       [-1.28956018, -1.61644772,  0.93094934, -0.34641016],
       [-0.3363478 , -0.3592106 ,  0.93094934, -0.34641016],
       [-1.51833115,  0.

In [ ]:
import numpy as np

w = np.array([1,2,3,4])
b = 1
y_pred = (x_train*w).sum(axis=1) + b
y_pred

array([-1.08085449, 12.76687543, -1.15711148, -1.0045975 , -1.04765039,
       -3.29230721, -0.97139339, -3.29030076,  4.36258302,  4.515097  ,
       -3.36655775,  0.66612544, -3.52107819,  1.0092819 , -2.11524825,
        1.35243836, -3.33043571, 12.76687543, -3.21404376,  1.16179588,
        4.43884001,  1.27618137,  4.66761099, -2.03899126, -1.23336847,
       12.76687543, -2.07711976, -1.00952189])

In [ ]:
((y_train - y_pred)**2).mean()

3078.96073888176

In [ ]:
def compute_cost(x, y, w, b):
    y_pred = (x*w).sum(axis=1) + b
    cost = ((y - y_pred)**2).mean()
    return cost

In [ ]:
w = np.array([1,2,3,4])
b = 1
cost = compute_cost(x_train, y_train, w, b)
cost

3078.96073888176

In [ ]:
y_pred = (x_train*w).sum(axis=1) + b
b_gradient = (y_pred - y_train).mean()
w_gradient = np.zeros(x_train.shape[1])

for i in range(x_train.shape[1]):
    w_gradient[i] = (x_train[:, i]*(y_pred - y_train)).mean()

w_gradient, b_gradient

(array([-6.81549145e+00, -1.45135548e+01,  1.03860207e+01,  3.37146121e-03]),
 -52.842857142857156)

In [ ]:
def compute_gradient(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  b_gradient = (y_pred - y).mean()
  w_gradient = np.zeros(x.shape[1])

  for i in range(x.shape[1]):
      w_gradient[i] = (x[:, i]*(y_pred - y)).mean()
  return w_gradient, b_gradient

w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)
w_gradient, b_gradient

(array([-6.81549145e+00, -1.45135548e+01,  1.03860207e+01,  3.37146121e-03]),
 -52.842857142857156)

In [ ]:
learning_rate = 0.001
w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)
print(compute_cost(x_train, y_train, w, b))
w = w - w_gradient*learning_rate
b = b - b_gradient*learning_rate
w, b
print(compute_cost(x_train, y_train, w, b))

3078.96073888176
3072.649541677409


In [ ]:
np.set_printoptions(formatter={'float': '{: .2e}'.format})
def gradient_descent(x, y, w_init, b_init, cost_function, gradient_function, learning_rate, iterations, p_iter=1000):
  c_hist = []
  w_hist = []
  b_hist = []

  w = w_init
  b = b_init

  for i in range(iterations):
    w_gradient, b_gradient = gradient_function(x, y, w, b)

    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    cost = cost_function(x, y, w, b)

    c_hist.append(cost)
    w_hist.append(w)
    b_hist.append(b)


    if i%p_iter == 0:
      print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient: .2e}")

  return w, b, w_hist, b_hist, c_hist

In [ ]:
w_init = np.array([1, 2, 3, 4])
b_init = 0
learning_rate = 1.0e-2
run_iter = 10000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, compute_cost, compute_gradient, learning_rate, run_iter)

Iteration     0 : Cost  3.1207e+03, w: [ 1.07e+00  2.15e+00  2.90e+00  4.00e+00], b:  5.38e-01, w_gradient: [-6.82e+00 -1.45e+01  1.04e+01  3.37e-03], b_gradient: -5.38e+01
Iteration  1000 : Cost  2.3510e+01, w: [ 5.76e+00  1.49e+01 -1.07e+00 -4.23e+00], b:  5.38e+01, w_gradient: [-3.70e-02 -1.87e-02 -2.60e-02  3.08e-02], b_gradient: -2.32e-03
Iteration  2000 : Cost  2.3503e+01, w: [ 5.85e+00  1.50e+01 -1.00e+00 -4.30e+00], b:  5.38e+01, w_gradient: [-5.55e-04 -2.42e-04 -3.81e-04  4.32e-04], b_gradient: -1.00e-07
Iteration  3000 : Cost  2.3503e+01, w: [ 5.85e+00  1.50e+01 -1.00e+00 -4.30e+00], b:  5.38e+01, w_gradient: [-8.12e-06 -3.36e-06 -5.38e-06  6.35e-06], b_gradient: -4.34e-12
Iteration  4000 : Cost  2.3503e+01, w: [ 5.85e+00  1.50e+01 -1.00e+00 -4.30e+00], b:  5.38e+01, w_gradient: [-1.19e-07 -4.69e-08 -7.62e-08  9.31e-08], b_gradient: -3.50e-13
Iteration  5000 : Cost  2.3503e+01, w: [ 5.85e+00  1.50e+01 -1.00e+00 -4.30e+00], b:  5.38e+01, w_gradient: [-1.73e-09 -6.55e-10 -1.08e

In [ ]:
w_final, b_final

(array([ 5.85e+00,  1.50e+01, -1.00e+00, -4.30e+00]), 53.84285714285679)

In [ ]:
y_pred = (w_final*x_test).sum(axis=1) + b_final
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

y_pred  y_test
14  60.531512    62.4
29  44.370233    41.6
22  65.600000    63.6
33  56.200168    45.2
20  44.147087    43.8
18  22.187264    26.5
28  28.658478    29.7
8   45.709105    40.7

In [ ]:
compute_cost(x_test, y_test, w_final, b_final)

22.63314958140529

In [ ]:
# 5.3 碩士以上 城市A
# 7.2 高中以下 城市B
x_real = np.array([[5.3, 2, 1, 0], [7.2, 0, 0, 1]])
x_real = sc.transform(x_real)
y_real = (w_final*x_real).sum(axis=1) + b_final
y_real

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([ 6.70e+01,  2.17e+01])